language: php

php:
- 5.4
- 5.5
- 5.6

before_script:
- mkdir ../libraries
- git clone --branch=master --depth=100 --quiet git://github.com/UnionOfRAD/lithium.git ../libraries/lithium
- git submodule update --init --recursive

script: ../libraries/lithium/console/li3 test --filters=Profiler tests/cases
